# Form implementation generated from reading ui file 'display/origin_files/testsWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 417)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTextQuestion = QtWidgets.QLabel(Form)
        self.lblTextQuestion.setText("")
        self.lblTextQuestion.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTextQuestion.setObjectName("lblTextQuestion")
        self.verticalLayout.addWidget(self.lblTextQuestion)
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.btnFirstAnswer = QtWidgets.QPushButton(Form)
        self.btnFirstAnswer.setObjectName("btnFirstAnswer")
        self.verticalLayout.addWidget(self.btnFirstAnswer)
        self.btnSecondAnswer = QtWidgets.QPushButton(Form)
        self.btnSecondAnswer.setObjectName("btnSecondAnswer")
        self.verticalLayout.addWidget(self.btnSecondAnswer)
        self.btnThirdAnswer = QtWidgets.QPushButton(Form)
        self.btnThirdAnswer.setObjectName("btnThirdAnswer")
        self.verticalLayout.addWidget(self.btnThirdAnswer)
        self.btnFourAnswer = QtWidgets.QPushButton(Form)
        self.btnFourAnswer.setObjectName("btnFourAnswer")
        self.verticalLayout.addWidget(self.btnFourAnswer)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btnFirstAnswer.setText(_translate("Form", "НАЖМИТЕ, ЧТОБЫ НАЧАТЬ"))
        self.btnSecondAnswer.setText(_translate("Form", "НАЖМИТЕ, ЧТОБЫ НАЧАТЬ"))
        self.btnThirdAnswer.setText(_translate("Form", "НАЖМИТЕ, ЧТОБЫ НАЧАТЬ"))
        self.btnFourAnswer.setText(_translate("Form", "НАЖМИТЕ, ЧТОБЫ НАЧАТЬ"))
